### ISSUE TITLE
Segmentation fault in unpigz

### ISSUE THREAD

**Issue by Wqrld** [madler/pigz#119]
unpigz 2.6 Running on an ubuntu 22.04, ryzen 7900, Linux 6.5.0-26-generic version. Some machines seem to be having issues with unpigz causing segmenation faults. Pigz seems unaffected.

Unfortunately i do not have much information to work from, but i will try my best to give as much information as possible.

Both the unpigz command fails on files compressed with pigz, and also unpigz as ran by docker or by tar. Running unpigz on another machine with the same setup works fine. The crashes seem very consistent.

```
[Tue Apr 23 18:49:05 2024] unpigz[1834534]: segfault at 107 ip 00007d14ae35cd65 sp 00007fffe9c6ad00 error 4 in libz.so.1.2.11[7d14ae353000+11000] likely on CPU 8 (core 10, socket 0)
[Tue Apr 23 18:49:05 2024] Code: 0f 11 67 68 90 4c 89 f0 4d 89 e6 49 89 c4 41 83 fd 05 0f 86 9d fb ff ff 8b 44 24 68 3d 01 01 00 00 0f 86 8e fb ff ff 4c 89 e7 <48> 8b 74 26 08 4d 89 f6 49 89 fe 48 8b 7c 24 10 89 46 20 48 89 7e
[Tue Apr 23 18:51:40 2024] unpigz[1834761]: segfault at 107 ip 0000760dba1a0d65 sp 00007ffe0ef71540 error 4 in libz.so.1.2.11[760dba197000+11000] likely on CPU 6 (core 8, socket 0)
[Tue Apr 23 18:51:40 2024] Code: 0f 11 67 68 90 4c 89 f0 4d 89 e6 49 89 c4 41 83 fd 05 0f 86 9d fb ff ff 8b 44 24 68 3d 01 01 00 00 0f 86 8e fb ff ff 4c 89 e7 <48> 8b 74 26 08 4d 89 f6 49 89 fe 48 8b 7c 24 10 89 46 20 48 89 7e
[Tue Apr 23 18:56:25 2024] unpigz[1835223]: segfault at 107 ip 000074c334c45d65 sp 00007fff0760f060 error 4 in libz.so.1.2.11[74c334c3c000+11000] likely on CPU 9 (core 11, socket 0)
[Tue Apr 23 18:56:25 2024] Code: 0f 11 67 68 90 4c 89 f0 4d 89 e6 49 89 c4 41 83 fd 05 0f 86 9d fb ff ff 8b 44 24 68 3d 01 01 00 00 0f 86 8e fb ff ff 4c 89 e7 <48> 8b 74 26 08 4d 89 f6 49 89 fe 48 8b 7c 24 10 89 46 20 48 89 7e
[Tue Apr 23 18:56:35 2024] unpigz[1835246]: segfault at 107 ip 00007c55d52dad65 sp 00007fff12ae1d00 error 4 in libz.so.1.2.11[7c55d52d1000+11000] likely on CPU 8 (core 10, socket 0)
```

```
Reading symbols from unpigz...
(No debugging symbols found in unpigz)
[New LWP 1835388]
[New LWP 1835389]

warning: Section `.reg-xstate/1835388' in core file too small.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/unpigz -d -c'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/1835388' in core file too small.
#0  0x000079dbae94ad65 in inflateBack () from /lib/x86_64-linux-gnu/libz.so.1
[Current thread is 1 (Thread 0x79dbae93e000 (LWP 1835388))]
(gdb) bt
#0  0x000079dbae94ad65 in inflateBack () from /lib/x86_64-linux-gnu/libz.so.1
#1  0x00005a147185cbac in ?? ()
#2  0x00005a147185f475 in ?? ()
#3  0x00005a14718543bf in ?? ()
#4  0x000079dbae629d90 in __libc_start_call_main (main=main@entry=0x5a1471853c40, argc=argc@entry=3, argv=argv@entry=0x7fffdb6b8308) at ../sysdeps/nptl/libc_start_call_main.h:58
#5  0x000079dbae629e40 in __libc_start_main_impl (main=0x5a1471853c40, argc=3, argv=0x7fffdb6b8308, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffdb6b82f8)
    at ../csu/libc-start.c:392
#6  0x00005a14718544ce in ?? ()

```

**Comment by madler** [comment]
> Running unpigz on another machine with the same setup works fine.

Might one conclude then that there's something wrong with that machine?

**Comment by Wqrld** [comment]
> > Running unpigz on another machine with the same setup works fine.
> 
> Might one conclude then that there's something wrong with that machine?

That was my initial conclusion too, and it might be correct, but since it only happens with unpigz and no other application on the machine, i assumed there would at least be some relation.

If you have never seen this issue before and do not see an obvious cause, you are free to close; But i wanted to open an issue either way to see if someone else had experienced this before.
